spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    passwrod:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  jwt:
    secret: fjklsdfkljsklfjelfafaflalafkklfjllfkkkkk
